server:
  port: 4000
aws:
  region: ap-southeast-1
  bucket-name: dath
spring:
  data:
    web:
      pageable:
        max-page-size: 50
        default-page-size: 5
  datasource:
    url: jdbc:postgresql://localhost:3000/dath
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
#    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
#        Turn on the following options when tunning persistence layer performance
#        generate_statistics: true
#        session:
#          events:
#            log:
#              LOG_QUERIES_SLOWER_THAN_MS=1:
#    #        enable_lazy_load_no_trans: true
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
